name: whitelabel_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: 7.3.1
  package_info_plus: 8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  assets:
    # How to bundle assets based on flavor
    # https://github.com/bizz84/flutter-tips-and-tricks/blob/main/tips/0147-bundle-assets-based-on-flavor/index.md
    - path: assets/blue/
      flavors:
        - blue
    # TODO: add all the remaining paths for each flavor

# TODO: Add flutter_flavorizr config for each flavor